# Dependencies
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false


# Setup
title:            Highlight
tagline:          'Blog of Abhishek Warokar'
description:      ''
url:              http://apollonian11.github.io
baseurl:          /

author:
  name:           'Abhishek Warokar'
  url:            http://apollonian11.github.io

gems:
 - jekyll-paginate
 - jekyll-gist

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/apollonian11/apollonian11.github.io
